### ISSUE TITLE
If something goes wrong, tell the reason.

### ISSUE THREAD

**Issue by Nibbels** [shield-9/u2f-login#11]
I looked at your Code and tried some things to fail registering.

What if I register a Key which is already registered?
- Screenshot: http://prntscr.com/6duyk0
- (Error Code 4 at End of data.errorCode)

What if I block Crome to identify like this message:
- http://prntscr.com/6dutg9
- 'Block' Gives this: http://prntscr.com/6dutmz
- (Error Code 2 at End of data.errorCode)

So I went into admin.js and changed this:
http://prntscr.com/6duu5n

var meaning = '';

if(data.errorText.indexOf("Error code: 2") > -1){
	meaning = 'You did not allow the Website do identify your Security Key'+'\n\n'
}else if(data.errorText.indexOf("Error code: 4") > -1){
	meaning = 'This Security Stick already seems to be registered.'+'\n\n'						
}
																
alert(
	meaning + 'Sorry, we are failed to register your security key.\n'
	+ ' * Error Code: ' + data.errorCode + '\n'
	+ ' * Status Message, Browser-side Error Code: ' + data.errorText
);

**Comment by shield-9** [comment]
Thanks, @Nibbels.
But basically, you can send me patch by Pull Request.

And you must include all 5 error codes. Each error code means:
1. Other Error
2. Bad Request
3. Configuration Unsupported
4. Device Ineligible
5. Timeout

See also: Page 6 of http://fidoalliance.org/specs/fido-u2f-v1.0-ps-20141009/fido-u2f-javascript-api-ps-20141009.pdf

I'm waiting your Pull Request!
