### ISSUE TITLE
"Non-administrator" cannot register Tokens

### ISSUE THREAD

**Issue by Nibbels** [shield-9/u2f-login#12]
![admin](https://cloud.githubusercontent.com/assets/3265671/6542101/3ec4e572-c4ef-11e4-9c4d-10f6e0647cc9.png)
![not_admin](https://cloud.githubusercontent.com/assets/3265671/6542102/418b0e08-c4ef-11e4-9ddb-299486a81dcd.png)
![screen2](https://cloud.githubusercontent.com/assets/3265671/6542103/476fee6a-c4ef-11e4-90d2-6f3574e158a4.png)

Whenever I am another Type of Moderator than Administrator, I cannot see admin(.min).js is included. So the Register-Button has no effect.

I am currently searching for the reason of this.

Greetings

**Comment by shield-9** [comment]
Thank you for reporting!

I'll look into this issue early this week.

**Comment by shield-9** [comment]
Sorry for late, it's fixed now!
