### ISSUE TITLE
Issues With Plugin Activation

### ISSUE THREAD

**Issue by tonynmrk** [shield-9/u2f-login#15]
Plugin could not be activated because it triggered a fatal error. 

Parse error: syntax error, unexpected ... /wp-content/plugins/u2f-login-master/u2f-login.php on line 143

Would LOVE to test out the plugin. I just received a small batch of U2F keys from France. But I keep getting the above error.

**Comment by shield-9** [comment]
What version of PHP are you using?
We supports PHP 5.5+ only.

**Comment by tonynmrk** [comment]
The default version installed on my shared hosting package is 5.4. I followed the documentation provided by my host to change php files to be processed with 5.5. However, no luck yet.

**Comment by shield-9** [comment]
Did you use "Download ZIP" link at https://github.com/shield-9/u2f-login?
It won't work.

Please use git command instead.

**Comment by tonynmrk** [comment]
I followed the instructions from this plugin documentation. Could you please elaborate on "git submodule update --init" do I need to request SSH access from my hosting provider? This is what I did to try and install the plugin. I used "Download Zip" to get the files.

Installation
Upload the u2f folder to the /wp-content/plugins/ directory.
Activate the plugin through the 'Plugins' menu in WordPress

**Comment by shield-9** [comment]
That readme file is written for stable release (near future).
If you don't know well about 'git' command, it is hard to use this plugin during development.

Please wait until the release of version 1.0.0.
