### ISSUE TITLE
Trying to activate the plugin

### ISSUE THREAD

**Issue by koenveelenturf** [shield-9/u2f-login#16]
Hi,

It seems like the plugin is broken. I've a Wordpress website (4.1.1) with PHP >5.5 and MySQL >5.5 running. This is the error message I get from Wordpress:

Fatal error: Parse error: syntax error, unexpected '{' in /[...]/plugins/u2f-login-master/u2f-login.php on line 143.

Cheers,
Koen

**Comment by koenveelenturf** [comment]
Whoops. Now I've logged in, I see that someone else also posted an issue for this problem. Sorry!
But for the record: I'm running PHP 5.5.31 and MySQL 5.5.31.

**Comment by shield-9** [comment]
#15
