### ISSUE TITLE
Installation instructions are unclear

### ISSUE THREAD

**Issue by acolomb** [shield-9/u2f-login#20]
In the installation instructions, it says to "Upload the u2f folder to the /wp-content/plugins/ directory."
1. It's not clear where to find a `u2f/` folder, as the repository does not contain one named like that.
2. Downloading the code using the "Download ZIP" button provided by Github seems to work at first, but then renders a Wordpress installation completely broken after upload.  That's because the Git submodule in `lib/php-u2flib-server` is not contained within the download.  One needs to check out the code, then run `git submodule update --init`.

Could you please provide a downloadable ZIP file for each release, ready to upload using Wordpress' own upload function?

**Comment by shield-9** [comment]
It's instructions for installation via WordPress.org Plugin Directory.
This repository is just for development.

**Comment by acolomb** [comment]
This plugin cannot be found in the Wordpress Plugin Directory. Is the documentation just prepared for an eventual release to be uploaded there?

But still, it's very confusing to have non-working instructions here on the Github project homepage. Especially since the obvious choice for an unsuspecting user is to press the "Download ZIP" button which yields a dangerously broken ZIP file that will break the user's Wordpress installation hard.

Better documentation for the early adopters would be great (maybe separate the README.md for Github from the plugin description?), but a working release ZIP package (even for unstable / alpha releases) would be even greater.

Would you mind reopening this issue? The problem still persists and visitors should be warned at least.

**Comment by shield-9** [comment]
This is development repository and for git users.
The plugin will be uploaded to WordPress.org soon. (The URL will be https://wordpress.org/plugins/u2f-login/ )
