### ISSUE TITLE
Trying to activate plugin on wordpress 4.2.2 causes a parsing error

### ISSUE THREAD

**Issue by miawgogo** [shield-9/u2f-login#22]
Error

> Parse error: syntax error, unexpected '{' in [path redacted]/wp-content/plugins/u2f-login-master/u2f-login.php on line 142

**Comment by shield-9** [comment]
What is your PHP version?

**Comment by miawgogo** [comment]
I forgot to update this issue for new infomation,

The vps hoster that the site is on Cpanel says it is 5.5 put php says it is at 5.
