### ISSUE TITLE
commit 47f9165 or bd4221d breaks browsers with chrome extension installed

### ISSUE THREAD

**Issue by aarcane** [shield-9/u2f-login#23]
I have the chrome extension installed and used by other sites for u2f.  One of the following commits broke the ability to use the u2f-login with chrome extension installed.  Not needing the chrome extension is all well and good, but if it's present, u2f should still continue to function.

**Comment by shield-9** [comment]
That Chrome extension should not be installed to use this plugin.

FYI, we are working on [2FA feature as a WordPress Core feature](https://github.com/georgestephanis/two-factor).
