### ISSUE TITLE
Wordpress site wont load when plugin is installed.

### ISSUE THREAD

**Issue by JDogHerman** [shield-9/u2f-login#24]
When I load the plugin into my wordpress site the site will not load any data. My page responds with a blank page.

I loaded the plugin by using a git clone from the repo.
I renamed the repo to 'u2f'
I set the permissions of the 'utf' folder to 774 and changed the owner from root (used for the git clone) to www-data. The apache service user.

I am using these versions:
PHP 5.5.9-1ubuntu4.6, 
MySql 5.5.41-0ubuntu0.14.04.1 
Wordpress 4.3.1

I was able to get back into my wordpress site after renaming the u2f folder to something else, but when the plugin was enabled no page would show content on my site.

Anyone have ideas on how to fix this?

**Comment by aarcane** [comment]
You have to properly load all the submodules. I had a similar problem.
Google git submodule

**Comment by JDogHerman** [comment]
Thank you @aarcane 

I got the plugin fixed by going to plugins directory under wp-content/plugins deleting the old repo then cloning a new repo using

:# git clone --recursive https://github.com/shield-9/u2f-login

Then enabling the plugin.

Thanks again!
