### ISSUE TITLE
Feature Request: Don't present U2F when using non supported browser.

### ISSUE THREAD

**Issue by JDogHerman** [shield-9/u2f-login#27]
I would like to see that the U2F option is not shown when a non U2F browser is used. Maybe watch the user-agent of the browser?

**Comment by shield-9** [comment]
You can send pull request for this. But we are working on [2FA feature as a WordPress Core feature](https://github.com/georgestephanis/two-factor).

**Comment by JDogHerman** [comment]
So is u2f built into https://github.com/georgestephanis/two-factor
