### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by jeanmalha** [shield-9/u2f-login#4]
Hello,

I upgraded to PHP 5.5, Wordpress 4.1, MySQL 5.5.31-0+wheezy1 and when I activate the plugin I get only blank pages.

Is there something I need to do specifically or that I can check?

Thanks for this development.

Feel free to tell me if I should log this as an issue.

Cheers,

Jean

**Comment by shield-9** [comment]
Please enable debug mode and send me PHP error log. ( http://codex.wordpress.org/Debugging_in_WordPress )

**Comment by shield-9** [comment]
No reply from reporter.
