### ISSUE TITLE
Please reconsider use of AGPLv3

### ISSUE THREAD

**Issue by darconeous** [shield-9/u2f-login#5]
Maybe I'm missing something, but the use of AGPLv3 in this case seems like it would almost certainly prevents this code from being used on sites like Wordpress.com because its use would require wordpress.com to release all of it's source code under the AGPLv3.

If the goal of this plugin is to increase adoption of U2F as quickly as possible, it might be worthwhile reconsidering the use of the "AGPLv3" license... Perhaps going with a "GPLv2(or later)" license instead.

**Comment by shield-9** [comment]
"To close the ASP loophole" is primal reason of using AGPLv3.

And this plugin is designed to work with *unaltered* and latest version of WordPress, PHP, MySQL and Apache.
Altered softwares (including WP.com) are not supported.
