### ISSUE TITLE
Security: Object Cast from Userland Data

### ISSUE THREAD

**Issue by StormTide** [shield-9/u2f-login#8]
https://github.com/shield-9/u2f-login/blob/master/u2f-login.php#L309

See: https://www.owasp.org/index.php/PHP_Object_Injection, https://bugs.php.net/bug.php?id=68710, etc..

**Comment by minisu** [comment]
Can you describe a possible attack for this particular case?

**Comment by StormTide** [comment]
Its a classic object injection vulnerability. See the owasp link above for how that works.

**Comment by shield-9** [comment]
I think https://github.com/yubico/php-u2flib-server is the best place to discus this.

**Comment by minisu** [comment]
Both of the pages that @StormTide linked to uses the `unserialize` method to unserialize a string. However, the code in `u2f-login.php` uses casting to cast an array to an object, which is a completely different thing. The object created by casting something to `object` [will not have any methods][1] (so not affected by his first link), [nor will it be created using the unserialize method][1] (so not affected by his second link).

With this being said; I'm a beginner when it comes to PHP, so I might be missing something.

[1]: http://php.net/manual/en/language.types.object.php#language.types.object.casting
